name: Build documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/ped'
  ARTIFACT: 'webHelpPED2-all.zip'
  DOCKER_VERSION: '241.16003'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}
          verbose: true
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          run: |
            echo "Current directory:"
            pwd
            echo "Directory contents:"
            ls -R
            echo "INSTANCE: ${{ env.INSTANCE }}"
            echo "ARTIFACT: ${{ env.ARTIFACT }}"
            echo "DOCKER_VERSION: ${{ env.DOCKER_VERSION }}"
            echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}